config/routes.rb
Cenci3::Application.routes.draw do
  delete 'logout' => 'sessions#destroy', :as => 'logout'
  post 'login' => 'sessions#create', :as => 'login'
  resources :enrollments
  resources :accounts do
    post 'approve' => 'accounts#approve', :as => 'approval'
    post 'register_pin' => 'accounts#register_pin', :as => 'register_pin'
  end
  resources :agents
  root :to => 'dashboards#index'
end

app/models/account.rb
class Account < User
  include Workflow
  authenticates_with_sorcery!

  field :address, :type => String
  field :phone, :type => String
  field :id_type, :type => String
  field :id_number, :type => String
  field :agree_to_terms, :type => DateTime
  field :approved_at, :type => DateTime
  field :state, :type => Symbol

  has_one    :provider_pin
  has_many   :registered_pins, :class_name => 'ProviderPin', :inverse_of => :registered_by
  belongs_to :approved_by, :class_name => 'Agent', :inverse_of => :approved_accounts

  belongs_to :parent,   :class_name => 'Account', :inverse_of => :children
  has_many   :children, :class_name => 'Account', :inverse_of => :parent

  validates :address, :presence => true
  validates :phone, :presence => true
  validates :id_type, :presence => true
  validates :id_number, :presence => true
  validates :agree_to_terms, :presence => true
  validates :state, :presence => true

  scope :pending,  where(:state => :pending)
  scope :approved, where(:state => :approved)

  workflow_column :state
  workflow do
    state :pending do
      event :approve, :transitions_to => :approved
    end
    state :approved
  end

  def approve(agent)
    self.approved_by = agent
    self.approved_at = DateTime.now
  end

  def pin
    self.username
  end

  after_create :send_welcome_email!
  after_create :send_account_pending_email!
  before_save  :update_geneology!

  def send_welcome_email!
    AccountMailer.welcome_email(self).deliver
  end

  def send_account_pending_email!
    AdminMailer.account_pending_email(self).deliver
  end

  def update_geneology!
    return unless self.parent.nil?
    return if self.provider_pin.nil?
    return if self.provider_pin.registered_by.nil?
    self.parent = self.provider_pin.registered_by
  end

  def self.approve_by_account_id(account_id, agent)
    account = find(account_id)
    raise "Account not found #{account_id}!" unless account
    account.approve!(agent)
    AccountMailer.approval_email(account).deliver
  end

  def self.create_with_provider_pin(account_params)
    provider_pin = ProviderPin.find(account_params.delete(:provider_pin))
    account = new(account_params)
    return account unless account.save
    return account unless provider_pin.assign!(account)
    unless provider_pin.registered_by.nil?
      provider_pin.registered_by.children << account
    end
    account.save
    account
  end

end

app/models/agent.rb
class Agent < User
  authenticates_with_sorcery!
  has_many :approved_accounts, :class_name => 'Account', :inverse_of => :approved_by
end

app/models/pin.rb
class Pin
  include Mongoid::Document
  include Mongoid::Timestamps

  field :pin, :type => Integer
  field :provider, :type => String

  validates :pin, :presence => true, :numericality => true, :uniqueness => true
  validates :provider, :presence => true, :inclusion => { :in => AppConfig.providers }

  def self.find_by_pin(pin)
    Pin.where(:pin => pin).limit(1).first || pin_not_found
  end

  def self.pin_not_found
    pin = Pin.new
    pin.errors[:pin] << 'Pin not found!'
    pin
  end
end

app/models/provider_pin.rb
class ProviderPin
  include Mongoid::Document
  include Mongoid::Timestamps
  include Workflow

  field :pin, :type => Integer
  field :provider, :type => String
  field :state, :type => Symbol
  field :registered_at, :type => DateTime

  belongs_to :account
  belongs_to :registered_by, :class_name => 'Account', :inverse_of => :registered_pins

  validates :pin, :presence => true, :numericality => true, :uniqueness => true
  validates :provider, :presence => true, :inclusion => { :in => AppConfig.providers }
  validates :state, :presence => true

  scope :loaded,   where(:state => :loaded)
  scope :assigned, where(:state => :assigned)

  workflow_column :state
  workflow do
    state :loaded do
      event :assign,   :transitions_to => :assigned
      event :register, :transitions_to => :registered
    end
    state :registered do
      event :assign, :transitions_to => :assigned
    end
    state :assigned
  end

  def assign(account)
    self.account = account
  end

  def register(account)
    self.registered_by = account
    self.registered_at = DateTime.now
  end

  def self.find_by_pin(pin)
    pin = pin.to_s[0..9].to_i rescue nil
    where(:pin => pin).limit(1).first
  end

  def self.register_by_pin(pin, registered_by)
    pin = where(:pin => pin).first
    return false unless pin
    pin.register!(registered_by)
  end

end

app/models/user.rb
class User
  include Mongoid::Document
  include Mongoid::Timestamps
  authenticates_with_sorcery!

  field :name, :type => String
  field :username, :type => String
  field :email, :type => String, :default => nil

  validates :name, :presence => true
  validates :username, :presence => true, :uniqueness => true
  validates :email, :uniqueness => true

  def agent?
    self._type == 'Agent'
  end

  def account?
    self._type == 'Account'
  end

end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  before_filter :find_provider_pin!, :only => [ :new, :create ]
  before_filter :normalize_agree_to_terms!, :only => [ :create ]
  before_filter :require_login, :only => [ :show, :register_pin ]
  before_filter :require_agent, :only => [ :approve ]

  def new
    @account = Account.new(:provider_pin => @provider_pin)
  end

  def create
    @account = Account.create_with_provider_pin(params[:account])
    unless @account.valid?
      render :new
    else
      auto_login @account
      flash[:notice] = "Thank you for enrolling #{@account.name}!"
      flash[:notice] << 'We sent you an email, holla back yo!' unless @account.email.blank?
      redirect_to account_path(@account)
    end
  end

  def show
  end

  def approve
    Account.approve_by_account_id(params[:account_id], current_user)
    redirect_to user_path(current_user)
  end

  def register_pin
    if ProviderPin.register_by_pin(params[:register_pin][:pin], current_user)
      redirect_to user_path(current_user), :notice => "Thank you for registering a pin #{current_user.name}!"
    else
      redirect_to user_path(current_user), :alert => "Pin not found!"
    end
  end

  private

    def find_provider_pin!
      @provider_pin = ProviderPin.find(params[:provider_pin_id]||params[:account][:provider_pin])
      unless @provider_pin
        flash[:error] = 'Pin not found!'
        return redirect_to new_enrollment_path
      end
    end

    def normalize_agree_to_terms!
      agree_to_terms = params[:account].delete(:agree_to_terms)
      params[:account][:agree_to_terms] = [ true, 1, '1' ].include?(agree_to_terms) ? DateTime.now : nil
    end

end

app/controllers/agents_controller.rb
class AgentsController < ApplicationController
  before_filter :require_agent

  def show
    @approved_accounts = Account.approved
    @pending_accounts = Account.pending
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  def require_agent
    redirect_to root_url, :alert => 'You must be an agent to view this page' unless current_user.agent?
  end

  def user_path(user)
    return new_enrollment_path if user._type == 'User'
    send "#{user._type.downcase}_path", user
  end

  def current_user_path
    user_path(current_user)
  end

end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController

  def index
    return redirect_to current_user_path if logged_in?
    redirect_to new_enrollment_path
  end

end

app/controllers/enrollments_controller.rb
class EnrollmentsController < ApplicationController
  def new
    @provider_pin = ProviderPin.new
  end

  def create
    @provider_pin = ProviderPin.find_by_pin(params[:provider_pin][:pin])
    unless @provider_pin
      render :new
    else
      redirect_to new_account_path(:provider_pin_id => @provider_pin.id)
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    user = login(params[:session][:username],
                 params[:session][:password],
                 params[:session][:remember_me])
    if user
      redirect_back_or_to user_path(user), :notice => "Welcome back #{user.name}!"
    else
      redirect_to new_enrollment_path, :alert => "Your info did not checkout dog!"
    end
  end

  def destroy
    logout
    redirect_to new_enrollment_path, :notice => 'See ya later dog!'
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/accounts/_form.html.slim
= simple_form_for @account do |f|
  = f.error_notification
  = f.input :pin, :disabled => true, :as => :string, :input_html => { :value => @provider_pin.pin.to_s }
  = f.input :name, :as => :string
  = f.input :email, :as => :email
  = f.input :address, :as => :string
  = f.input :phone, :as => :tel
  = f.input :id_number, :as => :string
  = f.input :id_type, :as => :string
  = f.input :password, :as => :password, :required => true
  = f.input :password_confirm, :as => :password, :required => true
  p.terms
    = render :partial => 'shared/terms'
  = f.input :agree_to_terms, :as => :boolean
  = f.input :provider_pin, :as => :hidden, :input_html => { :value => @provider_pin.id }
  = f.input :username, :as => :hidden, :input_html => { :value => @provider_pin.pin.to_s }
  = @account.errors.full_messages
  = f.submit   'Join the team!'

app/views/accounts/_register_pin_form.html.slim
h4 Register a Pin
= simple_form_for :register_pin, :url => account_register_pin_path(current_user), :html => { :id => "register_pin_form" }  do |f|
  = f.input :pin
  = link_to 'Register', '#', :onclick => "$('#register_pin_form').submit()"

app/views/accounts/_registered_pins.html.slim
div id="registered_pins"
  = render :partial => 'register_pin_form'
  h4 Registered Pins
  - current_user.registered_pins.each do |registered_pin|
    p id="registered_pin_#{registered_pin.id}" = registered_pin.pin

app/views/accounts/new.html.slim
= render :partial => 'form'

app/views/accounts/show.html.slim
= render :partial => 'registered_pins'

app/views/agents/_approved_accounts.html.slim
div id="approved_accounts"
  h4 Aproved Accounts
  - @approved_accounts.all.each do |approved_account|
    p id="approved_account_#{approved_account.id}" = approved_account.name

app/views/agents/_pending_accounts.html.slim
div id="pending_accounts"
  h4 Pending Accounts
  - @pending_accounts.all.each do |pending_account|
    p id="pending_account_#{pending_account.id}"
      = simple_form_for "pending_account_approval", :url => account_approval_path(pending_account), :html => { :id => "pending_account_approval_form_#{pending_account.id}" } do |f|
        = link_to "Approve #{pending_account.name}", '#', :onclick => "$('#pending_account_approval_form_#{pending_account.id}').submit()", :id => "pending_account_approval_link_#{pending_account.id}"

app/views/agents/show.html.slim
= render :partial => 'approved_accounts'
= render :partial => 'pending_accounts'

app/views/enrollments/_form.html.slim
= simple_form_for @provider_pin, :url => enrollments_path do |f|
  = f.error_notification
  = f.input  :pin
  = f.submit 'Enroll Me!'

app/views/enrollments/new.html.slim
= render :partial => "form"

app/views/layouts/application.html.slim
doctype html
html
head
  title Cenci3
  = stylesheet_link_tag    "application"
  = javascript_include_tag "application"
  = csrf_meta_tags

body

  p.notice = notice
  p.alert = alert

  - if current_user
    = render :partial => 'shared/logout_form'
  - else
    = render :partial => 'shared/login_form'


  = yield

app/views/shared/_login_form.html.slim
= simple_form_for :session, :url => login_path, :method => :post, :html => { :id => "login_form" } do |f|
  = f.input :username, :as => :string
  = f.input :password, :as => :password
  = f.input :remember_me, :as => :boolean
  = link_to 'Login', '#', :onclick => "$('#login_form').submit()"

app/views/shared/_logout_form.html.slim
= simple_form_for :session, :url => logout_path, :method => :delete, :html => { :id => "logout_form" } do |f|
  = link_to 'Logout', '#', :onclick => "$('#logout_form').submit()"

app/views/shared/_terms.html.slim
h4.term Them Termz

p.terms You agree to do my bidding, however, wherever, whenever...And some such other stuff...yo...